package com.project.CafeManagement.POJO;

import java.io.Serializable;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.NamedQuery;
import lombok.Data;

@NamedQuery(name = "User.findByEmailId", query = "select u from User u where u.email=:email")

@NamedQuery(name = "user.getAllUsers", query = "SELECT new com.project.CafeManagement.wrapper.userWrapper(u.id, u.name, u.contactnumber, u.email, u.status, u.role,u.password) FROM User u where u.role='user'")

@NamedQuery(name = "user.updateStatus ", query = "UPDATE User u SET u.status = :status WHERE u.id = :id")

@NamedQuery(name = "user.getAllUsers", query = "SELECT new com.project.CafeManagement.wrapper.userWrapper(u.id, u.name, u.contactnumber, u.email, u.status, u.role,u.password) FROM User u where u.role='Admin'")

@Data
@DynamicUpdate
@DynamicInsert
@Entity(name = "User")
public class User implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id")
	private Integer id;

	@Column(name = "name")
	private String name;

	public Integer getId() {
		return id;
	}
//
//	public void setId(String id) {
//		this.id = id;
//	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getContactnumber() {
		return contactnumber;
	}

	public void setContactnumber(String contactnumber) {
		this.contactnumber = contactnumber;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRole() {
		return role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Column(name = "email")
	private String email;

	@Column(name = "Contactnumber")
	private String contactnumber;

	@Column(name = "password")
	private String password;

	@Column(name = "Status")
	private String status;

	@Column(name = "Role")
	private String role;

	// Getters and setters are generated by Lombok's @Data annotation, but you can
	// add custom ones if needed
}
